### ISSUE TITLE
Example using yaml file throws error

### ISSUE THREAD

**Issue by Relequestual** [mheap/convert-action#6]
My action file is action.yaml as opposed to action.yml.

I do the following as per the readme here...

`npx convert-action dist/index.js my-subfolder/action.yml`

This throws.

`Error: Unable to parse YAML file [dist/index.js]: end of the stream or a document separator is expected`

It seems to be trying to parse the js file as YAML.

Am I doing something wrong here or should this work?

**Comment by mheap** [comment]
Reading the code it looks like I got the args in reverse. Try the following:

npx convert-action my-subfolder/action.yml dist/index.js

**Comment by Relequestual** [comment]
Ah, good to know, thanks.
It turns out, I'm using a compound action to use node.js v18, so this action is actually not helpful for my use anyway.

Feel free to close when you've updated the readme =]

**Comment by mheap** [comment]
This is resolved in #7
